### ISSUE TITLE
Make commands such as !fight and !hug delete after a set amount of time

### ISSUE THREAD

**Issue by volcanicer** [FoggyIO/Wilfred#27]
**Is your feature request related to a problem? Please describe.**
The issue is that both commands and can start spamming the chat, causing Staff to constantly have to !cleanuser Wilfred.
**Describe the solution you'd like**
We should make Wilfred delete the messages after one minute of being sent.
**Describe alternatives you've considered**
Make the commands have an extended cooldown of 1 hour.

_Edited By FoggyIO @ 19:12 18/09/2018 - Fixed Formatting_

**Comment by FoggyIO** [comment]
The !hug command itself doesn't actually spam, !fight on the other hand can cause spam in the unlikely event that the fight continues for a long period of time (maybe we could limit the number of turns and cause it to default to a draw?). Since the commands are limited to staff members and staff members only, I don't want to start adding restrictions or workarounds. Staff shouldn't be spamming them and if they do then they should be warned not to.

**Keeping issue open for further discussion**

**Comment by FoggyIO** [comment]
**Issue Closed - Inactive for 14+ Days**
