### ISSUE TITLE
!daily command

### ISSUE THREAD

**Issue by Cobble8** [FoggyIO/Wilfred#60]
**!daily** - Gives the user a certain amount of coins each day (This part is optional but maybe add like a streak type thing? Like day 1 you get 250 coins, Day 2 300 coins, etc.)

**Comment by BluePhoenixGame** [comment]
Maybe, but this makes so that users can just do the command then just dont care about the server. Maybe do so that after a number of messages the command will be done automagically

**Comment by Cobble8** [comment]
If they didn't care about the server why would they do it **-_-**

**Comment by GeorgeCY2** [comment]
@BluePhoenixGame well it's true but he's suggesting that kind of system where "the more days you get your dailys, bigger the reward will be" so if they message and command and don't care about it in 2+ days, they will be back to Day 1 like so, so you can imagine someone inactive types it once, he gets only 250$ and us chatting almost every day getting our dailys is more than 250$ every day rather than a guy who types it and doesn't care

**Comment by GeorgeCY2** [comment]
also not bad of a suggestion but imo it takes a while and skills to make it, i may can do it, but im scared of failing the PR and stuff like this

**Comment by GeorgeCY2** [comment]
so the command should be typed once and not multiple becaue it isn't necessary and it might count as "spamming only 3 times to get the daily" @BluePhoenixGame

**Comment by GeorgeCY2** [comment]
ah and a tip that it doesn't meet the suggestion template @Cobble8, So idk of this will get declined for that reason

**Comment by BluePhoenixGame** [comment]
Ah, that is true.

**Comment by GeorgeCY2** [comment]
actually thinking about it, it's hard to PR this feature, due to that i must see how to do a check that **if** the **Member** didn't send in days < 2, then stay in day 1 forever and etc.

**Comment by Cobble8** [comment]
So Im not really much of a py coder anymore, Im more with js right now but feel free to correct me if if wrong, Couldn't you just do when the bot starts up people can use !daily then have a cooldown until they can use it again but after that cooldown expires, add another cooldown for 24 hours and if they don't use !daily in that time frame then it resets
 (And sorry about the incorrect formatting thing )

**Comment by FoggyIO** [comment]
Might add a daily streak bonus for people who are active (6+ messages) each day, the bonus increases each time until a maximum of a 7 day streak.

**Comment by Cobble8** [comment]
I like this idea

**Comment by FoggyIO** [comment]
**Suggestion Approved**

After a discussion with the staff team, we have decided to approve your idea. I am now working on an implementation that will work as follows: 

250 -> 500 -> 1000 -> 1500 -> 2000 -> 2500 -> 3000 -> 3000 after sending 6 messages in that day, if the streak is lost you go back to 250 and have to build it up again. The bonus will reset every 24 hours (probably when the bot restarts) and failure to obtain your bonus within that 24 hour period will result in your streak being reset.

Expect to see this implemented sometime soon. 

In the meantime, if you have anything else you would like to add feel free to below.

**Comment by GeorgeCY2** [comment]
alright that's a good daily combo!

**Comment by FoggyIO** [comment]
**Update:**

We've decided to do something a little different with **!daily** - Instead of it being a certain amount of balance, you'll be able to unlock different types of rewards. You'll get given 3 cards from which you must choose one. There will be different tiers of rarity and as you streak your daily bonus your chances of getting rarer items increases.
