### ISSUE TITLE
Make g!stats used for everyone

### ISSUE THREAD

**Issue by GeorgeCY2** [FoggyIO/Wilfred#64]
Instead of everyone mentioning staff to check their stats, like how much severe punishments they have, Messages sent, The Standing and etc. I feel like this should be used for everyone, for these kind of situations, like for example: what if the staff are offline and i wanna check these informations?

**Comment by FoggyIO** [comment]
HarryThorpe:

"g!stats is a Staff+ **guardian** command for assessing information about a user, there is literally no need for anyone to need access to this command since it provides nothing useful to them. If you're interested in your punishment history you can do "!history <yourid>". The command itself wasn't meant to become publicly known, nor is it something staff are really meant to be publicly showcasing. It exists to help staff decide whether a user is sketchy or not, not as a useful statistics tool. With that said I won't be releasing the Staff+ Permissions constraint"

**Issue Closed - Denied**
